name: CI/CD pipeline for Lift-o-Meter backend

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Backend:
    runs-on: ubuntu-latest
    steps:
    - name: Get repo contents
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Cache Maven dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2   
    - name: Maven clean install
      run:
        mvn clean install
    - name: Maven tests
      run:
        mvn test
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      if: ${{ github.event_name == 'push' }}
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "lift-o-meter-back"
        heroku_email: "tommi.niittymies@gmail.com"
        healthcheck: "https://lift-o-meter-back.herokuapp.com/api/test/healthcheck"
        checkstring: "Up and running..."
        rollbackonhealthcheckfailed: true
